import Head from "next/head";
import CameraFeed from '../components/CameraFeed';


export default function Home() {
  return (
    <>
      <Head>
        <title>Emotion Recognition Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Emotion Recognition Demo</h1>
        <CameraFeed />
      </div>
    </>
  );
}
